.PHONY: build clean watch

OUTPUT_DIR :=$(abspath $(dir $(CURDIR))/output)

build:
	@echo "Coming soon..."

clean:
	@echo "Nothing to clean."

watch:
	@echo "Coming soon..."

test:
	mkdir -p $(OUTPUT_DIR)
	lualatex -output-directory=$(OUTPUT_DIR) test.tex
	lualatex -output-directory=$(OUTPUT_DIR) test.tex